version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mnt/mysql/data:/var/lib/mysql
      - ./mnt/mysql/conf.d:/etc/mysql/conf.d
      - ./mnt/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  liferay:
    image: ibaiborodine/liferay-portal-ce
    depends_on:
      - mysql
    environment:
      LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED: "false"
      LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED: "false"
    ports:
      - "80:8080"
      - "11311:11311"
    volumes:
      - ./mnt/liferay/base:/etc/opt/liferay
      - ./mnt/liferay/data/document_library:/opt/liferay/data/document_library
      - ./mnt/liferay/deploy:/opt/liferay/deploy
    restart: unless-stopped
